branches:
  - master
  - stable
projects:
  BedcoreProtect:
    path: ""
    icon: resources/bedcoreprotect_logo.png
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.3.0
        branch: "4.0"
      - src: JackMD/UpdateNotifier
        version: ^1.1.0
        branch: "API-4.0.0"
...
