--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/matcracker/BedcoreProtect
branches:
- master
projects:
  BedcoreProtect:
    includeDirs:
      vendor: vendor
    path: ""
    libs:
      - src: poggit\libasynql
        version: ^3.0
...
