branches:
  - master
  - stable
projects:
  BedcoreProtect:
    includeDirs:
      vendor: vendor
    path: ""
    icon: resources/bedcoreprotect_logo.png
    stub: "stub.php"
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.2
        branch: "4.0"
...
